[package]
name = "allowance-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
allowance-types.workspace = true
allowance-config.workspace = true
allowance-service.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
